### ISSUE TITLE
Unknown command!Error: Missing command!Error: Access denied!

### ISSUE THREAD

**Issue by stargazerwna** [brablc/sitebar#13]
Hello I have upgraded to 3.4-svn and using the plugin: https://addons.mozilla.org/en-US/firefox/addon/sitebar-client-for-firefox-40x/  in some admin functions when I hit the "return" button I get an error message.

I believe this is something that has to do with the plugin.
Any ideas?

**Comment by brablc** [comment]
I hope this was fixed long time ago.
