### ISSUE TITLE
PHP 7 is still not working

### ISSUE THREAD

**Issue by etofi** [brablc/sitebar#16]
Sorry but it is still not working.

![unbenannt](https://cloud.githubusercontent.com/assets/19774831/20425794/8a7b2086-ad7c-11e6-8a75-ee605769f5ba.PNG)

**Comment by brablc** [comment]
What command / action did you try to execute?

**Comment by etofi** [comment]
sitebar.XXXX.de/command.php?command=Add%20Link&url=http%3A//www.google.de/

**Comment by brablc** [comment]
Where did you take the source code from? Are you sure you are using https://github.com/brablc/sitebar/tree/php7 branch?

**Comment by brablc** [comment]
No response.
