### ISSUE TITLE
Can't add new bookmarks

### ISSUE THREAD

**Issue by tsadan** [brablc/sitebar#19]
When I try to add a new bookmark, I get this message:
`Invalid query: 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'expires' at row 1`

My SiteBar Version is ver. 3.5-svn

**Comment by brablc** [comment]
3.5-svn does not sound familiar to me. What PHP version do you have and where did you get the source code from?

**Comment by brablc** [comment]
And more importantly what MySQL version are you running.

**Comment by tsadan** [comment]
Hi,

my mysql version is
`mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64)`

I copie the sitebar-version information from the webinterface 
![image](https://user-images.githubusercontent.com/1706347/35159068-65740dda-fd39-11e7-9572-fe688079f320.png)
 
I cloned the php7.0 sitebar branch from git.

My php version:
`php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies`

Best regards
Markus

**Comment by brablc** [comment]
This could be a problem with `sql_mode`, I tried to fix it in 73bf84affc9f8746a20f407d1def21441241ce49 . Please beware, that php7 branch is now gone. Master is now php7 compatible.
