### ISSUE TITLE
Invalid Query

### ISSUE THREAD

**Issue by dogskool** [brablc/sitebar#20]
I have installed the latest version and the link view is working fine.
I added the "Add Page to SiteBar" bookmarklet* to my Chrome and Firefox.
When I try to add a page to my SiteBar, I receive this error:
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'expires'

any idea how I can resolve this error?

**Comment by brablc** [comment]
Where did you get the latest version from? This sounds like issue #19.

**Comment by brablc** [comment]
Please provide output of `select @@sql_mode;` and reopen.
