### ISSUE TITLE
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'expires'

### ISSUE THREAD

**Issue by dogskool** [brablc/sitebar#22]
>Please provide output of select @@sql_mode; and reopen.
select @@sql_mode;

@@sql_mode |  
-- | --
NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by brablc** [comment]
Thank you, and do you still have a problem, even with latest version?

**Comment by dogskool** [comment]
Now the error reads "

Error
Function name must be a string search►
Source file

File: ../public_html/bkmk/command.php:1028

1018:                }
1019:                elseif (isset($params['type']) &&  $params['type'] == 'callback')
1020:                {
1021:                    if (isset($params['show_label']) && $params['show_label'])
1022:                    {
1023:    ?>
1024:                        <div class="label"><?php echo SB_T($name).$star?></div>
1025:    <?php
1026:                    }
1027:    
1028:                    $this->$params['function'](isset($params['params'])?$params['params']:null);
1029:                }
1030:                elseif (isset($params['type']) &&  $params['type'] == 'callbackextern')
1031:                {
1032:                    $params['function'](isset($params['params'])?$params['params']:null);

Call stack

    /home/helpcom/public_html/bkmk/command.php:1125	source  SB_CommandWindow->writeFields(arguments)

    /home/helpcom/public_html/bkmk/command.php:6526	source  SB_CommandWindow->writeForm() "

**Comment by brablc** [comment]
Please create a new issue for this, this is not related to database at all. Please add details how to reproduce the problem.

**Comment by brablc** [comment]
However, this problem is probably fixed by 022cc9b.
