### ISSUE TITLE
issue with 'Add Page to Sitebar'

### ISSUE THREAD

**Issue by dogskool** [brablc/sitebar#24]
Uploaded the latest version Release 3.6
Tried to add webpage to Bookmark list and received the following error.
Error
Function name must be a string search►
Source file

File: ../public_html/bkmk/command.php:1028

1018: }
1019: elseif (isset($params['type']) && $params['type'] == 'callback')
1020: {
1021: if (isset($params['show_label']) && $params['show_label'])
1022: {
1023: ?>
1024:

1025: <?php
1026: }
1027:
1028: $this->$params'function';
1029: }
1030: elseif (isset($params['type']) && $params['type'] == 'callbackextern')
1031: {
1032: $params'function';

Call stack

../public_html/bkmk/command.php:1125	source  SB_CommandWindow->writeFields(arguments)

../public_html/bkmk/command.php:6526	source  SB_CommandWindow->writeForm() "

--

Call stack

    ..public_html/bkmk/command.php:1125	source  SB_CommandWindow->writeFields(arguments)

    1115:            <input type="hidden" name="<?php echo $param?>" value="<?php echo $value?>">
    1116:    <?php
    1117:                }
    1118:            }
    1119:    
    1120:            $enabled = false;
    1121:    
    1122:            // Add missing propeties
    1123:            $hasOptional = $this->enrichFields() && !$this->um->getParam('user','expert_mode');
    1124:    
    1125:            $this->writeFields($optional=false, $customButton, $enabled);
    1126:    
    1127:            if ($hasOptional)
    1128:            {
    1129:    ?>

 ../public_html/bkmk/command.php:6526	source  SB_CommandWindow->writeForm()

    6516:            echo '<p>'."\r";
    6517:        }
    6518:    
    6519:        // If we have no errors or ignore them
    6520:        if (!$cw->hasErrors() || $cw->showWithErrors || $cw->hasHandledErrors()==$cw->hasErrors())
    6521:        {
    6522:            if ($cw->fields)
    6523:            {
    6524:                $noerrors = !$cw->hasErrors();
    6525:    
    6526:                $cw->writeForm();
    6527:    
    6528:                // Some late errors?
    6529:                if ($noerrors && $cw->hasErrors())
    6530:                {

**Comment by brablc** [comment]
Can you please double check, that you already have 022cc9b885d92e840fc2c89e23d968477f5c4284 ? I fixed it couple of minutes before you opened the issue.

**Comment by dogskool** [comment]
made the correction and I was able to get to the submit form and on clicking submit I received the following error:
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'changed'

INSERT INTO sitebar_link (name, url, favicon, target, private, is_feed, comment, validate, added, nid)
VALUES ('Travelpro� | Highest Quality Luggage for the Experienced Traveler', 'https://www.travelpro.com/', '', '', 0, 0, '', 1, now() , 987)
