### ISSUE TITLE
error with 'Add to Sitebar'

### ISSUE THREAD

**Issue by dogskool** [brablc/sitebar#25]
Updated to the latest version and I was able to get to the submit form and on clicking submit I received the following error:
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'changed'

INSERT INTO sitebar_link (name, url, favicon, target, private, is_feed, comment, validate, added, nid)
VALUES ('Travelpro� | Highest Quality Luggage for the Experienced Traveler', 'https://www.travelpro.com/', '', '', 0, 0, '', 1, now() , 987)

**Comment by kdtcat** [comment]
I could circumvent the problem by altering the following sitebar_link table  fields to "Null"

ALTER TABLE `sitebar_link` 
	CHANGE `changed` `changed` DATETIME NULL DEFAULT NULL;
	
ALTER TABLE `sitebar_link` 
	CHANGE `visited` `visited` DATETIME NULL DEFAULT NULL;
	
ALTER TABLE `sitebar_link` 
	CHANGE `tested` `tested` DATETIME NULL DEFAULT NULL;

**Comment by dogskool** [comment]
I applied this and I am getting this:
*Invalid query:* 1978: Incorrect default value '0000-00-00 00:00:00' for
column 'expires'

**Comment by kdtcat** [comment]
You can try the following as well 

ALTER TABLE sitebar_message
CHANGE expires expires DATETIME NULL DEFAULT NULL;

**Comment by dogskool** [comment]
this query gives me this message:
Error

*SQL query:*

ALTER TABLE sitebar_message
CHANGE expires expires DATETIME NULL DEFAULT NULL

*MySQL said: *[image: Documentation]
<http://cpanel.help357.com/cpsess8306010552/3rdparty/phpMyAdmin/url.php?url=https%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.7%2Fen%2Ferror-messages-server.html>
#1146 - Table 'helpcom_bkmk.sitebar_message' doesn't exist

**Comment by kdtcat** [comment]
Well, I checked all sitebar tables with PHPMyAdmin and this table was the only one which had a Datetime field named 'expires' not set to NULL.

**Comment by dogskool** [comment]
for some reason, I do not have this table in my database.
How can I add it? or how can I get an updated database?

**Comment by kdtcat** [comment]
This is an extract of the install.sql:

`CREATE TABLE `sitebar_message`
(
  `mid` int(10) unsigned NOT NULL auto_increment,
  `uid` int(10) unsigned NOT NULL,
  `gid` int(10) unsigned,
  `sent` datetime NOT NULL default CURRENT_TIMESTAMP,
  `expires` datetime,
  `role` varchar(10),
  `format` varchar(10),
  `to_label` text,
  `subject` text,
  `message` text,
  PRIMARY KEY  (`mid`)
)`

**Comment by dogskool** [comment]
created table, then ran the previous NULL query.

received this error on trying to add book mark:
*Invalid query:* 1978: Incorrect default value '0000-00-00 00:00:00' for
column 'expires'

**Comment by kdtcat** [comment]
Last hint I can give is checking the sitebar_cache table. I saw in older releases that this table had a field 'expires'.  You can delete this field with
`ALTER TABLE sitebar_cache
DROP expires;`

or may be better:

`ALTER TABLE sitebar_cache
CHANGE expires expires DATETIME NULL DEFAULT NULL`

P.S. Don't forget to backup your DB before.

**Comment by dogskool** [comment]
SUCCESS.

I am now able to save bookmarks.

Thank you for taking the time to help me.

**Comment by brablc** [comment]
A new upgrade script may solve the problem for other users: c703a44  .
