### ISSUE TITLE
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'expires'

### ISSUE THREAD

**Issue by eviltel** [brablc/sitebar#27]
Hi!

I tried to move my sitebar installation version 3.3.9 to a new server. This was not possible. The new server has php 7.2 and only the mysqli module. 3.3.9 used mysql. So I did an upgrade to version 3.6 at the same time.

The new server runs MariaDB 10.1.31.

I did:
1. Installed yesterdays (20-jul-2018) git-master (3.6).
1. Imported the old database.
1. Opened the index.php and got asked for the db-connection parameters.
1. Tested the connection, put the file in the adm folder and refreshed index.php.
1. Got asked to upgrade my db and clicked on Upgrade.

The first thing I got:
```
Invalid query: 1978: Incorrect default value '0000-00-00 00:00:00' for column 'expires'
```

I checked the issues on github for similar errors and found that the db upgrade did not run successfully. For ex. I did not have the tables: `sitebar_message` and `sitebar_message_folder` which come with `upgrade_3.3.12.sql` -- same as in https://github.com/brablc/sitebar/issues/25#issuecomment-392108729.

## Investigation
I droped the database, imported again from 3.3.9 and did run all `upgrade_xxx.sql` manually.
Everything worked fine but the last one `upgrade_3.5.sql`.

I had to switch these two statements:
```sql
UPDATE `sitebar_user`
   SET `visited` = NULL
   WHERE `visited` = '0000-00-00 00:00:00';
```
and
```sql
ALTER TABLE `sitebar_user`
    CHANGE `visited` `visited` DATETIME NULL DEFAULT NULL;
```
because one could not set the NULL value in a column not allowing it.

Next problem:
The Update did not work yet. There was no error but the database did not change any rows although there was a row with `0000-00-00 00:00:00`. The WHERE clause did not work.
```sql
UPDATE `sitebar_user`
   SET `visited` = NULL
   WHERE `visited` = '0000-00-00 00:00:00';
```

The statement worked after I changed it to:
```sql
UPDATE `sitebar_user`
   SET `visited` = NULL
   WHERE date(`visited`) = '0000-00-00 00:00:00';
```

This however did not solve my `Invalid query` problem.

## Cleaning
Next step was to find all `0000-00-00 00:00:00` -- clearly a date my db does not like --  and update them with NULL.
```sql
ALTER TABLE `sitebar_cache` change `created` `created` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_cache` change `expires` `expires` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_config` change `changed` `changed` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_link` change `changed` `changed` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_link` change `added` `added` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_link` change `visited` `visited` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_link` change `tested` `tested` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_message` change `sent` `sent` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_message` change `expires` `expires` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_session` change `created` `created` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_token` change `issued` `issued` datetime  NULL DEFAULT NULL;
ALTER TABLE `sitebar_visit` change `visited` `visited` datetime  NULL DEFAULT NULL;

UPDATE `sitebar_cache` SET `expires` = NULL where date(`expires`) = '0000-00-00 00:00:00';
UPDATE `sitebar_link` SET `changed` = NULL where date(`changed`) = '0000-00-00 00:00:00';
UPDATE `sitebar_link` SET `visited` = NULL where date(`visited`) = '0000-00-00 00:00:00';
UPDATE `sitebar_link` SET `tested` = NULL where date(`tested`) = '0000-00-00 00:00:00';
```
The other tables had no '0000-00-00 00:00:00' saved so I didn't bother updating them.

After this sitebar came online. I get the index page, can login and so on. :-) Sitebar seems to work again.

## sql_mode
Just in case you ask for @@sql_mode:
I don't know what it had configured in the beginning.

In `upgrade_3.5.sql` one do `SET @@sql_mode = '';` and afterwards I get
```sql
select @@sql_mode;
NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

Tom

**Comment by brablc** [comment]
Thank you very much for your analysis which I seem to have missed. I may have a proper solution in c703a44, but it still may not be perfect.
