### ISSUE TITLE
Adding a bookmark without title -> Automatically get the title.

### ISSUE THREAD

**Issue by telefrancisco** [brablc/sitebar#3]
When adding a bookmark without adding a title, it shouldn't be enforced for users to insert the title manually or to get it by clicking on a button. Instead, it should get the title on his own.

**Comment by brablc** [comment]
Sorry, I did not notice that there are any issues on this repo, since its creation. But this does not look like bug but rather request for feature (although probably reasonable). I'm afraid I will only have enough time to sort out bugs.
