### ISSUE TITLE
You have to enable cookies in order to log-in or sign-up!

### ISSUE THREAD

**Issue by CarpetDog** [brablc/sitebar#32]
When attempting to login, I am getting this error

You have to enable cookies in order to log-in or sign-up!

I have cookies enabled
I have tried different browsers

Any ideas?
![2021-01-25_22-48-15](https://user-images.githubusercontent.com/15056214/105775922-8f8f5800-5f5f-11eb-98b3-45cd92380163.png)

**Comment by WBTMagnum** [comment]
Do you use the browser add-on? There was a similar problem (#30) and a fix (#31). Maybe that helps.

If not, some more details might be helpful:
* Sitebar version
* PHP version

**Comment by brablc** [comment]
It seems that #31 probably broke setting cookies in php 7.3 and above. You can try now.
