### ISSUE TITLE
Login not possible with PHP 7.3 and 7.4

### ISSUE THREAD

**Issue by alhauser** [brablc/sitebar#33]
I cannot login to Sitebar anymore under PHP 7.3 and 7.4. Using PHP 7.2, it works.

* Setup: latest Sitebar version from Github (3.6.2) on an own server. Set the PHP version on the server to 7.2, 7.3, and 7.4.
* Tested: logging in to Sitebar in a normal as well as a private / incognito window under Firefox 85 and Chrome 88, both under Linux and Mac OS X
* Result:
  * Under PHP 7.2, login works as intended.
  * Under PHP 7.3 and 7.4, login is not possible, but a login attempt also doesn't provide an error message. When trying to log in with the correct username and password, Sitebar returns back to the public page showing public bookmarks.
  * The behaviour is reproducible under all browsers listed above.
* Issue: it seems Sitebar does not generate cookies under PHP 7.3 and PHP 7.4; Sitebar cookies are visible when Sitebar is run under PHP 7.2.

**Comment by brablc** [comment]
It looks like commit #31 broke login. Hopefully fixed in the last commit. But may be we will need a fix for Chrome again.

**Comment by brablc** [comment]
Fixed by commit c87cbd73edac2c6c78ef0111ef95389af7a166bc  .

**Comment by alhauser** [comment]
Great, thanks for fixing this, @brablc and @WBTMagnum !

Pulled the latest Sitebar version from Github, confirming the problem is gone under PHP 7.4 using Firefox 88 and Chrome 90 under Linux.
