### ISSUE TITLE
Feature Request: Nginx configuration for Sitebar with multiple web-apps

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [brablc/sitebar#36]
For the life of me, I cannot figure out how to get Sitebar working with Nginx!
This does not work either: https://github.com/brablc/sitebar/issues/6

**EDIT:** I forgot to mention that I have php7.4-fpm listening on a separate dedicated socket for Sitebar

I recently installed Yunohost (YNH) on a separate machine and the distro presents a great example of sub-folder hosted multiple web apps. I think Sitebar would be a great alternative for the existing Bookmark apps there, and would provide your project with good exposure. The 2 bookmark apps that already exist in YNH are Sharrli (which stores the BM data in a .php file - ridiculous!) and Shiori (which lacks many features your project already has).

YNH is DEbian based, uses by default Mariadb, php7.3-fpm (Testing branch -Bullseye - uses 7.4) & Nginx. I'm not proficient in PHP, and I have not kept up with Nginx configuration recently so I lack the skills to be of assistance to you - sorry.

I sincerely hope to see Sitebar in the YNH apps collection.

**Comment by brablc** [comment]
Not sure how can I help you here. For Sitebar it should be completely transparent, whether it runs via TCP connection or Unix socket. It is just matter of nginx and php-fpm configuration. But I have tried to prepare docker compose that uses unix scoket:  https://github.com/brablc/sitebar-docker/tree/use_unix_socket
