### ISSUE TITLE
Install failure debugged & can't import Bookmarks

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [brablc/sitebar#37]
For incremental debugging, I installed apache2 and the PHP requirements.
* PHP 8.0.8, Zend Engine v4.0.8
* Apache/2.4.48

**This section as FYI:** I Debugged several problems in `inc/page.inc.php`:
* Lines 328 & 373: Replace '{}' with '[]'
* I doubt anyone uses PHP 6.0 anymore, lines 39 - 51 cause error. Fix or comment the lines out.
After above modifications, `sitebar/config.php` shows up,

I had other errors, but I'm unsure whether they were due to my mistakes or not. In any case, moving the sitebar folder to /var/www/html (Apache document root) solved those problems.

**IMPORT PROBLEM:**
There's no submit button when trying to import bookmark file (Firefox exported html).
If I try adding a single bookmark the 3 expected buttons are there.
There's an error message, but that's due to the "Codepage" dropdown not populating (and not important):
`[php:error] [pid 1680040] [client 127.0.0.1:34586] PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /var/www/html/sitebar/inc/localizer.inc.php:209\nStack trace:\n#0 /var/www/html/sitebar/inc/localizer.inc.php(209): vsprintf()\n#1 /var/www/html/sitebar/inc/localizer.inc.php(344): SB_Localizer->getText()\n#2 /var/www/html/sitebar/command.php(6181): SB_T()\n#3 /var/www/html/sitebar/command.php(1028): SB_CommandWindow->_buildCodepage()\n#4 /var/www/html/sitebar/command.php(1125): SB_CommandWindow->writeFields()\n#5 /var/www/html/sitebar/command.php(6526): SB_CommandWindow->writeForm()\n#6 {main}\n  thrown in /var/www/html/sitebar/inc/localizer.inc.php on line 209, referer: http://localhost/sitebar/index.php?uniq=1648085722
`

**Comment by brablc** [comment]
Fixed, sorry for quite a delay.
