### ISSUE TITLE
eregi deprecated

### ISSUE THREAD

**Issue by dethegeek** [brablc/sitebar#4]
Hi

After years searching for an alternative to proprietary cross browser bookmark sync tool, I found SiteBar. I was thinking about developing it myself. First, thank you very much for your efforts !

I wish to warn you about the deprecated function eregi :

Attention: Function eregi() is deprecated [converter.inc.php line 123]

**Comment by brablc** [comment]
Well that is embarrassing. I have probably wrong settings about notifications and did not notice anything since uploading it here. I have fixed the problem in 4307339e156995d2303ee62aff5020df311f3e37 . The code is obscure and does not make any sense, so I have deleted it all.
