### ISSUE TITLE
Warnung: Non-static method SB_Database::staticInstance() 

### ISSUE THREAD

**Issue by kidexx** [brablc/sitebar#9]
Dear all,

since my last upgrade of PHP to PHP Version 5.6.17 I get the following errors:

Warnung: Non-static method SB_Database::staticInstance() should not be called statically, assuming $this from incompatible context [usermanager.inc.php line 53]
...

more in attachment...
[sitebar_errors.txt](https://github.com/brablc/sitebar/files/111506/sitebar_errors.txt)

Best regards,

Alexander

**Comment by kidexx** [comment]
Hi, I changed it - where it pooped in my installation up. I created a pull request.

**Comment by brablc** [comment]
Thanks for pull request. I have accepted it.

**Comment by kidexx** [comment]
Hi,

that is cool. First time for me with github - that I submitted something.

If I find again problem I will try to fix it :-)

Best regards,

Alexander

Am 15.02.2016 um 21:47 schrieb Ondrej Brablc:
